export const TYPES = {
  Normal: 'white',
  Fight: 'white',
  Flying: 'white',
  Poison: 'white',
  Ground: 'white',
  Rock: 'white',
  Bug: 'white',
  Ghost: 'white',
  Steel: 'white',
  Fire: 'white',
  Water: 'white',
  Grass: 'white',
  Electra: 'white',
  Pyschic: 'white',
  Ice: 'white',
  Dragon: 'white',
  Dark: 'white',
  Fairy: 'white',
};
